export const GET_SYSTEM_LIST_REQUEST = 'app/NewProjectPage/GET_SYSTEM_LIST_REQUEST';
export const GET_SYSTEM_LIST_SUCCESS = 'app/NewProjectPage/GET_SYSTEM_LIST_SUCCESS';
export const SAVE_PROJECT_REQUEST = 'app/NewProjectPage/SAVE_PROJECT_REQUEST';
export const GET_ROOM_CATEGORIES_REQUEST = 'app/NewProjectPage/GET_ROOM_CATEGORIES_REQUEST';
export const GET_ROOM_CATEGORIES_SUCCESS = 'app/NewProjectPage/GET_ROOM_CATEGORIES_SUCCESS';
